"""Abstract base class for trading strategies."""

from abc import ABC, abstractmethod
from typing import Dict, List, Any
from dataclasses import dataclass
import pandas as pd

@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    action: str  # 'buy', 'sell', 'hold'
    confidence: float  # 0.0 to 1.0
    price: float
    quantity: int = 0
    reason: str = ""
    timestamp: pd.Timestamp = None
    reasoning: dict = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = pd.Timestamp.now()

class Strategy(ABC):
    """Abstract base class for all trading strategies."""
    
    name: str = "Base Strategy"
    description: str = "Abstract base strategy"
    
    def __init__(self, config: Dict[str, Any] = None):
        self.config = config or {}
        self.validate_config(self.config)
    
    @abstractmethod
    def generate_signals(self, data: pd.DataFrame) -> List[Signal]:
        """
        Generate trading signals based on market data.
        
        Args:
            data: DataFrame with OHLCV data, indexed by timestamp
                  Columns: open, high, low, close, volume
        
        Returns:
            List of Signal objects
        """
        pass
    
    @abstractmethod
    def get_parameters(self) -> Dict[str, Any]:
        """
        Get strategy parameters and their descriptions.
        
        Returns:
            Dictionary mapping parameter names to descriptions/defaults
        """
        pass
    
    @abstractmethod
    def validate_config(self, config: Dict[str, Any]) -> bool:
        """
        Validate strategy configuration parameters.
        
        Args:
            config: Configuration dictionary
        
        Returns:
            True if configuration is valid
            
        Raises:
            ValueError: If configuration is invalid
        """
        pass
    
    def get_name(self) -> str:
        """Get strategy name."""
        return self.name
    
    def get_description(self) -> str:
        """Get strategy description."""
        return self.description
    
    def get_config(self) -> Dict[str, Any]:
        """Get current strategy configuration."""
        return self.config.copy()
    
    def update_config(self, config: Dict[str, Any]) -> None:
        """Update strategy configuration."""
        self.validate_config(config)
        self.config.update(config)
    
    def _calculate_position_size(
        self, 
        signal: Signal, 
        portfolio_value: float, 
        risk_pct: float = 0.02
    ) -> int:
        """
        Calculate position size based on risk management rules.
        
        Args:
            signal: Trading signal
            portfolio_value: Current portfolio value
            risk_pct: Risk percentage per trade
        
        Returns:
            Number of shares to trade
        """
        risk_amount = portfolio_value * risk_pct
        shares = int(risk_amount / signal.price)
        return max(1, shares)  # Minimum 1 share
    
    def _format_signal_reason(self, indicators: Dict[str, float], action: str) -> str:
        """Format a human-readable reason for the signal."""
        reasons = []
        for indicator, value in indicators.items():
            reasons.append(f"{indicator}: {value:.3f}")
        
        return f"{action.upper()} - {', '.join(reasons)}"